include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    directives_ordering: true
    public_member_api_docs: true

analyzer:
  errors:
    avoid_print: ignore
    avoid_redundant_argument_values: ignore
    unused_local_variable: ignore
  exclude:
    - local_tools/**
